export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const ADD_DISCUSSION = 'ADD_DISCUSSION';
export const UPDATE_DISCUSSION = 'UPDATE_DISCUSSION';
export const DELETE_DISCUSSION = 'DELETE_DISCUSSION';
export const ADD_TODO = 'ADD_TODO';
export const ADD_BUG = 'ADD_BUG';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_BUG = 'UPDATE_BUG';
export const DELETE_BUG = 'DELETE_BUG';
export const ADD_NOT_ASSIGNED_MEMBER = 'ADD_NOT_ASSIGNED_MEMBER';
export const ADD_MEMBER_AT_PROJECT = 'ADD_MEMBER_AT_PROJECT';
export const DELETE_MEMBER_FROM_PROJECT = 'DELETE_MEMBER_FROM_PROJECT';
export const ACTIVITY_PREPARED = 'ACTIVITY_PREPARED';
export const ADD_WORK_PREVIEW = 'ADD_WORK_PREVIEW';
export const ADD_IS_MEMBER_AND_CREATOR = 'ADD_IS_MEMBER_AND_CREATOR';
export const PREPARE_DATA_FOR_DASHBOARD = 'PREPARE_DATA_FOR_DASHBOARD';
export const ALL_USER_LOADED = 'ALL_USER_LOADED';
export const LOADED_SELECTED_USER = 'LOADED_SELECTED_USER';

export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';
